# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from GridGame.models.base_model_ import Model
from GridGame import util


class Coord(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, x: int=None, y: int=None):  # noqa: E501
        """Coord - a model defined in Swagger

        :param x: The x of this Coord.  # noqa: E501
        :type x: int
        :param y: The y of this Coord.  # noqa: E501
        :type y: int
        """
        self.swagger_types = {
            'x': int,
            'y': int
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y'
        }
        self._x = x
        self._y = y

    @classmethod
    def from_dict(cls, dikt) -> 'Coord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Coord of this Coord.  # noqa: E501
        :rtype: Coord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> int:
        """Gets the x of this Coord.


        :return: The x of this Coord.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x: int):
        """Sets the x of this Coord.


        :param x: The x of this Coord.
        :type x: int
        """

        self._x = x

    @property
    def y(self) -> int:
        """Gets the y of this Coord.


        :return: The y of this Coord.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y: int):
        """Sets the y of this Coord.


        :param y: The y of this Coord.
        :type y: int
        """

        self._y = y
