# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from GridGame.models.base_model_ import Model
from GridGame.models.move import Move  # noqa: F401,E501
from GridGame import util


class IdMoveBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, move: Move=None):  # noqa: E501
        """IdMoveBody - a model defined in Swagger

        :param move: The move of this IdMoveBody.  # noqa: E501
        :type move: Move
        """
        self.swagger_types = {
            'move': Move
        }

        self.attribute_map = {
            'move': 'move'
        }
        self._move = move

    @classmethod
    def from_dict(cls, dikt) -> 'IdMoveBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The id_move_body of this IdMoveBody.  # noqa: E501
        :rtype: IdMoveBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def move(self) -> Move:
        """Gets the move of this IdMoveBody.


        :return: The move of this IdMoveBody.
        :rtype: Move
        """
        return self._move

    @move.setter
    def move(self, move: Move):
        """Sets the move of this IdMoveBody.


        :param move: The move of this IdMoveBody.
        :type move: Move
        """

        self._move = move
